/**
 * sandbox.ts
 * Opens a generated project in StackBlitz WebContainers.
 * Falls back to a download trigger if StackBlitz SDK is unavailable.
 */

export interface SandboxFiles {
  [path: string]: string;
}

/**
 * Open a set of files in StackBlitz using their JavaScript SDK.
 * If the SDK is not installed, falls back to a graceful message.
 */
export async function openInSandbox(files: SandboxFiles, projectName = "DevKit.AI Project") {
  try {
    // Dynamic import — works even if @stackblitz/sdk not yet installed
    const sdk = await import("@stackblitz/sdk" as any);
    sdk.default.openProject(
      {
        title: projectName,
        description: "Auto-generated by DevKit.AI",
        template: "node" as const,
        files,
      },
      { openFile: "src/index.js" }
    );
  } catch {
    // SDK not available — show instructions
    console.warn("StackBlitz SDK not available. Opening fallback.");
    window.open(
      `https://stackblitz.com/fork/node?title=${encodeURIComponent(projectName)}`,
      "_blank"
    );
  }
}

/**
 * Parse a zip Blob into a flat { path: content } record.
 * Uses JSZip if available, otherwise returns a minimal starter.
 */
export async function zipBlobToFiles(blob: Blob): Promise<SandboxFiles> {
  try {
    const JSZip = (await import("jszip" as any)).default;
    const zip = await JSZip.loadAsync(blob);
    const files: SandboxFiles = {};
    const entries = Object.entries(zip.files) as [string, any][];
    await Promise.all(
      entries.map(async ([path, file]) => {
        if (!file.dir) {
          files[path] = await file.async("string");
        }
      })
    );
    return files;
  } catch {
    return {
      "src/index.js": `require('dotenv').config();\nconst express = require('express');\nconst app = express();\napp.get('/healthz', (req, res) => res.json({ status: 'ok' }));\napp.listen(3000, () => console.log('Running on http://localhost:3000'));\n`,
      "package.json": JSON.stringify({ name: "devkit-project", version: "0.1.0", main: "src/index.js", scripts: { start: "node src/index.js" }, dependencies: { express: "^4.18.0", dotenv: "^16.0.0" } }, null, 2),
      ".env": "PORT=3000\n",
    };
  }
}

/**
 * Trigger a browser file download from a Blob.
 */
export function triggerBlobDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
