/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsSessionIdRouteImport } from './routes/results.$sessionId'
import { Route as GenerationSessionIdRouteImport } from './routes/generation.$sessionId'
import { Route as ConversationSessionIdRouteImport } from './routes/conversation.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSessionIdRoute = ResultsSessionIdRouteImport.update({
  id: '/results/$sessionId',
  path: '/results/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationSessionIdRoute = GenerationSessionIdRouteImport.update({
  id: '/generation/$sessionId',
  path: '/generation/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationSessionIdRoute = ConversationSessionIdRouteImport.update({
  id: '/conversation/$sessionId',
  path: '/conversation/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversation/$sessionId': typeof ConversationSessionIdRoute
  '/generation/$sessionId': typeof GenerationSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversation/$sessionId': typeof ConversationSessionIdRoute
  '/generation/$sessionId': typeof GenerationSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversation/$sessionId': typeof ConversationSessionIdRoute
  '/generation/$sessionId': typeof GenerationSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversation/$sessionId'
    | '/generation/$sessionId'
    | '/results/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversation/$sessionId'
    | '/generation/$sessionId'
    | '/results/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/conversation/$sessionId'
    | '/generation/$sessionId'
    | '/results/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationSessionIdRoute: typeof ConversationSessionIdRoute
  GenerationSessionIdRoute: typeof GenerationSessionIdRoute
  ResultsSessionIdRoute: typeof ResultsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$sessionId': {
      id: '/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof ResultsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation/$sessionId': {
      id: '/generation/$sessionId'
      path: '/generation/$sessionId'
      fullPath: '/generation/$sessionId'
      preLoaderRoute: typeof GenerationSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$sessionId': {
      id: '/conversation/$sessionId'
      path: '/conversation/$sessionId'
      fullPath: '/conversation/$sessionId'
      preLoaderRoute: typeof ConversationSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationSessionIdRoute: ConversationSessionIdRoute,
  GenerationSessionIdRoute: GenerationSessionIdRoute,
  ResultsSessionIdRoute: ResultsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
